# Yaml file
services: 
  # app service=====
  explogin-app: 
    build: 
       context: .
    container_name: ${CONTAINER_NAME}
    volumes:
      - .:/home/app
    depends_on: 
      - mongoes
    ports: 
      - "3050:3050"
    restart: always
    environment:
      - MONGO_PATH=mongodb://exp-db:27017/

  # Database sevice
  mongoes: 
    container_name: exp-db
    image: "${DATABASE_IMAGE_NAME}:latest"
    ports: 
      - "2717:27017"
    restart: always
    volumes: 
      - ${DATABASE_VOLUME_NAME}:/data/db

volumes: 
  mongodb-data:      
version: "3.2"
