# Yaml file
services: 

  explogin-apss: 
    build: 
       context: .
    container_name: ${CONTAINER_NAME}
    volumes:
      - .:/home/nodedummy/app
    depends_on: 
      - mongoes
    ports: 
      - "3050:3050"
    restart: always


  mongoes: 
    container_name: ${CONTAINER_DATABASE_NAME}
    image: "${DATABASE_IMAGE_NAME}:latest"
    ports: 
      - "27017:27017"
    # restart: always
    volumes: 
      - ${DATABASE_VOLUME_NAME}:/data/db

volumes: 
  mongodb-data:      
version: "3.2"
